### ISSUE TITLE
Broken on Activation

### ISSUE THREAD

**Issue by RonR-WebDesign** [Pross/reBusted#1]
Parse error: syntax error, unexpected '-', expecting ',' or ';' in /home/example/public_html/wp-content/plugins/rebusted/rebusted.php on line 19

**Comment by Pross** [comment]
Im not seeing this issue, what php version are you using? Anything exotic?

**Comment by RonR-WebDesign** [comment]
Thanks for the response…

 

PHP Version 5.4.45

Wordpress 4.9.5

 

Deactivated all plugs.  Still get the error.

 

 

I am getting a strange jQuery error:

 

script.js:34 Uncaught ReferenceError: jQuery is not defined.

 

Here's that code from theme file: script.js

 

// css helper

browser = function ($) {

    'use strict';

    var data = [

        { str: navigator.userAgent, sub: 'Chrome', ver: 'Chrome', name: 'chrome' },

        { str: navigator.vendor, sub: 'Apple', ver: 'Version', name: 'safari' },

        { prop: window.opera, ver: 'Opera', name: 'opera' },

        { str: navigator.userAgent, sub: 'Firefox', ver: 'Firefox', name: 'firefox' },

        { str: navigator.userAgent, sub: 'MSIE', ver: 'MSIE', name: 'ie' },

        { str: navigator.userAgent, sub: 'Trident/7.0', ver: 'rv', name: 'ie' }

    ];

    var v = function (s, n) {

        var i = s.indexOf(data[n].ver);

        return (i !== -1) ? parseFloat(s.substring(i + data[n].ver.length + 1)) : 0;

    };

    var result = { name: 'unknown', version: 0 };

    var html = $('html');

    for (var n = 0; n < data.length; n++) {

        if (!result[data[n].name]) {

            result[data[n].name] = false;

        }

        if ((data[n].str && (data[n].str.indexOf(data[n].sub) !== -1)) || data[n].prop) {

            result.name = data[n].name;

            result[result.name] = true;

            result.version = v(navigator.userAgent, n) || v(navigator.appVersion, n);

            html.addClass(result.name + ' ' + result.name + parseInt(result.version, 10));

        }

    }

    return result;

} (jQuery);  <-- line 24
