### ISSUE TITLE
PHP 8 Warning

### ISSUE THREAD

**Issue by midrocketdev** [Pross/reBusted#4]
reBusted is generating a huge amount of PHP Warnings in error log:
[09-Oct-2024 08:36:03 UTC] PHP Warning:  Array to string conversion in /wp-content/plugins/rebusted/rebusted.php on line 65

**Comment by Pross** [comment]
No issues here with PHP 8.3

Im thinking maybe you already have some code somewhere removing the ver?

**Comment by midrocketdev** [comment]
We are checking, we'll come back when we have more info

**Comment by midrocketdev** [comment]
We’ve done some investigating and found that some of the plugins we have installed are using an array() instead of a string in the version field within wp_enqueue_. While this is indeed poor practice from the plugin in question, it would be helpful if reBusted could handle this error without triggering a warning.

Here’s an example of the problematic code found in another plugin:
`wp_enqueue_script( 'example', '/js/example.js', array('jquery'), array() );`

And here's the correct approach, which works smoothly with reBusted:
`wp_enqueue_script( 'example', '/js/example.js', array('jquery'), null );`

If reBusted could account for this type of issue, it would prevent warnings from filling the logs.

**Comment by Pross** [comment]
The ver arg has always been string, bool or null. Never been array there, im actually suprised WP itself does not crap out or at least let you know in the logs with a _doing_it_wrong()

Whats the plugin doing this? Perhaps let them know

**Comment by midrocketdev** [comment]
You’re absolutely right, and it surprises us just as much that some plugins are being published like this. We've already notified the authors of a few of them, but we believe it’s more scalable for this to also be patched on your side. Unfortunately, we can’t always reach out to all plugin authors, and the same goes for your reBusted users.

**Comment by Pross** [comment]
```
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_script( 'testing-js', '/js/example.js', array('jquery'), array() );
});
```
This shows nothing in the logs, php 8.3 latest WP with debug enabled

**Comment by Pross** [comment]
```
	static public function wp_print_scripts() {

		global $wp_scripts, $wp_styles, $wp_version;

		foreach ( array( $wp_scripts, $wp_styles ) as $enqueue_list ) {
			if ( ! isset( $enqueue_list->__busted_filtered ) && is_object( $enqueue_list ) ) {
				foreach ( (array) $enqueue_list->registered as $handle => $script ) {
					$modification_time = self::modification_time( $script->src );
					if ( $modification_time ) {
						$version = is_string( $script->ver ) ? $script->ver : $wp_version;
						$version = $version . '-' . self::get_version_slug() . '-' . $modification_time;
						$enqueue_list->registered[ $handle ]->ver = $version;
					}
				}
				/**
				 * wp_print_scripts runs in header in footer and when called.
				 * Only run this modification once.
				 */
				$enqueue_list->__busted_filtered = true;
			}
		}
	}
```
